// static string Charizard()
//         {
//             var part1 = @"                 .' -,.__                                                  ".Pastel(Color.RoyalBlue);
//             var part2 = @"                  `.     `.__,                                             ".Pastel(Color.RoyalBlue);
//             var part3 = @"               .--'".Pastel(Color.RoyalBlue) + "  .._,''".Pastel(Color.OrangeRed) + "- '".Pastel(Color.OrangeRed) + "`.                                          ".Pastel(Color.RoyalBlue);
//             var part4 = @"              .".Pastel(Color.RoyalBlue) + "    .'         `'                                           ".Pastel(Color.OrangeRed);
//             var part5 = @"              `.".Pastel(Color.RoyalBlue) + @"   /          ,'                                           ".Pastel(Color.OrangeRed);
//             var part6 = @"                `".Pastel(Color.RoyalBlue) + "  '--.   ,-''                                             ".Pastel(Color.OrangeRed);
//             var part7 = @"                 `'".Pastel(Color.RoyalBlue) + @"`".Pastel(Color.Gold) + @"   |  \                                                ".Pastel(Color.OrangeRed);
//             var part8 = @"                    -.".Pastel(Color.Gold) + @" \, |                                                ".Pastel(Color.OrangeRed);
//             var part9 = @"                     `--Y.'".Pastel(Color.Gold) + @"      ___.                                      ".Pastel(Color.Silver);
//             var part10 = @"                          \".Pastel(Color.Gold) + @"     |._, \                                    ".Pastel(Color.Silver);
//             var part11 = @"                _.,".Pastel(Color.Silver) + "        `.".Pastel(Color.Gold) + "   <".Pastel(Color.WhiteSmoke) + "  <".Pastel(Color.WhiteSmoke) + @"\ \              _                    ".Pastel(Color.Silver);
//             var part12 = @"              ,' '".Pastel(Color.Silver) + "           `,".Pastel(Color.Gold) + @" `.   | \            ( `                   ".Pastel(Color.Silver);
//             var part13 = @"           ../, `.".Pastel(Color.Silver) + "            `".Pastel(Color.Gold) + "  |    .".Pastel(Color.Silver) + @"\`.".Pastel(Color.DarkRed) + @"           \ \_                 ".Pastel(Color.Silver);
//             var part14 = @"          ,'".Pastel(Color.Silver) + " ,..".Pastel(Color.DarkRed) + @"  .".Pastel(Color.Silver) + "           _.,".Pastel(Color.Salmon) + "'    ||".Pastel(Color.Silver) + @"\|".Pastel(Color.DarkRed) + "            )  ''.              ".Pastel(Color.Silver);
//             var part15 = @"         ,".Pastel(Color.Silver) + @" ,'   \".Pastel(Color.DarkRed) + @" \".Pastel(Color.Silver) + "         ,'".Pastel(Color.Salmon) + ".-.".Pastel(Color.PaleVioletRed) + "`-._,".Pastel(Color.Salmon) + "'  |           .".Pastel(Color.Silver) + "  _._".Pastel(Color.DarkRed) + "`.             ".Pastel(Color.Silver);
//             var part16 = @"       ,'".Pastel(Color.Silver) + @" /      \".Pastel(Color.DarkRed) + @" \".Pastel(Color.Silver) + "        `' ' `--".Pastel(Color.Salmon) + @"/   | \          /".Pastel(Color.Silver) + @" /   \ ".Pastel(Color.DarkRed) + @"\            ".Pastel(Color.Silver);
//             var part17 = @"     .'".Pastel(Color.Silver) + @"  /        \".Pastel(Color.DarkRed) + @" .         |\__ - _ ,'` `        /".Pastel(Color.Silver) + @" /     `.".Pastel(Color.DarkRed) + "`.          ".Pastel(Color.Silver);
//             var part18 = @"     |".Pastel(Color.Silver) + @"  '          .".Pastel(Color.DarkRed) + ".         `-...-'  |  `-'      /".Pastel(Color.Silver) + @" /        .".Pastel(Color.DarkRed) + " `.        ".Pastel(Color.Silver);
//             var part19 = @"     |".Pastel(Color.Silver) + @" /           |".Pastel(Color.DarkRed) + "|__           |    |          /".Pastel(Color.Silver) + @" /          `.".Pastel(Color.DarkRed) + " `.      ".Pastel(Color.Silver);
//             var part20 = @"    ,".Pastel(Color.Silver) + @" /            .".Pastel(Color.DarkRed) + @"   .          |    |         /".Pastel(Color.Silver) + @" /             `".Pastel(Color.DarkRed) + " `      ".Pastel(Color.Silver);
//             var part21 = @"   /".Pastel(Color.Silver) + @" /".Pastel(Color.DarkRed) + "          ,. ".Pastel(Color.WhiteSmoke) + "` ".Pastel(Color.DarkRed) + @"._".Pastel(Color.DarkRed) + @" `-_       |    |  _   ,-'".Pastel(Color.Silver) + @" /               `".Pastel(Color.DarkRed) + @" \     ".Pastel(Color.Silver);
//             var part22 = @"  /".Pastel(Color.Silver) + @" .".Pastel(Color.DarkRed) + "           \'`_".Pastel(Color.WhiteSmoke) + @" /.".Pastel(Color.WhiteSmoke) + " `-_".Pastel(Color.DarkRed) + @" \_,.  ,'    +-' `-'".Pastel(Color.Silver) + @"   /".Pastel(Color.DarkRed) + @"          .,-.".Pastel(Color.RoyalBlue) + @"   \".Pastel(Color.DarkRed) + @"`.    ".Pastel(Color.Silver);
//             var part23 = @" .".Pastel(Color.Silver) + @"  '".Pastel(Color.DarkRed) + "         .-f".Pastel(Color.WhiteSmoke) + "    ,'".Pastel(Color.WhiteSmoke) + "   `".Pastel(Color.DarkRed) + @"  ,/'        \".Pastel(Color.Silver) + " ,.-- -` ".Pastel(Color.DarkRed) + @",.    ".Pastel(Color.WhiteSmoke) + "   .'   '".Pastel(Color.RoyalBlue) + @"   \".Pastel(Color.DarkRed) + @" \   ".Pastel(Color.Silver);
//             var part24 = @" '".Pastel(Color.Silver) + @" /".Pastel(Color.DarkRed) + "          `.'".Pastel(Color.WhiteSmoke) + @"    |     .' /".Pastel(Color.Silver) + @"          \  ".Pastel(Color.Silver) + @"      '`_ /.".Pastel(Color.WhiteSmoke) + "   /".Pastel(Color.RoyalBlue) + " .,'`".Pastel(Color.OrangeRed) + @"    \`".Pastel(Color.DarkRed) + @"\  ".Pastel(Color.Silver);
//             var part25 = @" |".Pastel(Color.Silver) + @"'      _.-""`\".Pastel(Color.DarkRed) + @" `.    \ _,'_/`            \-, ".Pastel(Color.Silver) + " .-f".Pastel(Color.WhiteSmoke) + @"     ".Pastel(Color.Silver) + ",'".Pastel(Color.WhiteSmoke) + " ,".Pastel(Color.RoyalBlue) + " |   |".Pastel(Color.OrangeRed) + @"     |".Pastel(Color.DarkRed) + @"| ".Pastel(Color.Silver);
//             var part26 = @" |".Pastel(Color.Silver) + @"|    ,'      `.".Pastel(Color.DarkRed) + @" `.   '".Pastel(Color.Silver) + "       _,...._".Pastel(Color.Bisque) + @"      ".Pastel(Color.Silver) + " `.".Pastel(Color.Silver) + " '".Pastel(Color.WhiteSmoke) + "     /".Pastel(Color.Silver) + "  '".Pastel(Color.RoyalBlue) + "  |   '".Pastel(Color.OrangeRed) + @"     .".Pastel(Color.DarkRed) + @"|  ".Pastel(Color.Silver);
//             var part27 = @" |".Pastel(Color.Silver) + "|  ,'          `.".Pastel(Color.DarkRed) + " ;.,.---'".Pastel(Color.Silver) + " ,'        `.".Pastel(Color.Bisque) + @"   .  `-'  .-  ".Pastel(Color.Silver) + @"/".Pastel(Color.RoyalBlue) + "_ .'    ;".Pastel(Color.OrangeRed) + @"__".Pastel(Color.DarkRed) + @"  |".Pastel(Color.DarkRed) + @"|  ".Pastel(Color.Silver);
//             var part28 = @" |".Pastel(Color.Silver) + "| '              V".Pastel(Color.DarkRed) + "      /".Pastel(Color.Silver) + @" /            \".Pastel(Color.Bisque) + @" \ `\   ,'".Pastel(Color.Silver) + @"  ,' '.    ! | ".Pastel(Color.Gold) + @" \ |".Pastel(Color.DarkRed) + @"|  ".Pastel(Color.Silver);
//             var part29 = @" |".Pastel(Color.Silver) + "|/".Pastel(Color.DarkRed) + "            _,-------/".Pastel(Color.Silver) + @" '              \".Pastel(Color.Bisque) + @" |  `-'".Pastel(Color.Silver) + @"    (          /   ".Pastel(Color.Gold) + @"\|".Pastel(Color.DarkRed) + @"|  ".Pastel(Color.Silver);
//             var part30 = @" .".Pastel(Color.Silver) + " |          ,' .-   ,' |".Pastel(Color.Silver) + @"|               |".Pastel(Color.Bisque) + @" .-.".Pastel(Color.Silver) + "        `.      .'".Pastel(Color.Gold) + "     ||  ".Pastel(Color.Silver);
//             var part31 = @"  `".Pastel(Color.Silver) + "'        ,'    `'.'".Pastel(Color.Silver) + @"    |               |".Pastel(Color.Bisque) + @"/   `.        ".Pastel(Color.Silver) + "'. -.'".Pastel(Color.Gold) + "       `'  ".Pastel(Color.Silver);
//             var part32 = @"           /      ,'".Pastel(Color.Silver) + @"      |               |".Pastel(Color.Bisque) + @",'    \-.._,.'".Pastel(Color.Silver) + "/'               ".Pastel(Color.Bisque);
//             var part33 = @"          /.".Pastel(Color.Bisque) + "     /".Pastel(Color.Silver) + @"        .               .".Pastel(Color.Bisque) + @"       \".Pastel(Color.Silver) + "    .''                ".Pastel(Color.Bisque);
//             var part35 = @"           \ `...".Pastel(Color.Bisque) + @"\   _     ,".Pastel(Color.Silver) + @"'-.        .'".Pastel(Color.Bisque) + @"__        /".Pastel(Color.Silver) + "_.-'                   ".Pastel(Color.Bisque);
//             var part34 = @"          .`.".Pastel(Color.Bisque) + "   |".Pastel(Color.Silver) + @"         `.             /".Pastel(Color.Bisque) + @"         :".Pastel(Color.Silver) + "_,'.'                 ".Pastel(Color.Bisque);
//             var part36 = @"            `-.__ ".Pastel(Color.Bisque) + "`,  `'___.    ".Pastel(Color.Silver) + @">----''".Pastel(Color.Bisque) + @" |   `'___./                        ".Pastel(Color.Silver);
//             var part37 = @"                 .".Pastel(Color.WhiteSmoke) + "'        /           _.".Pastel(Color.Silver) + "'      /                        ".Pastel(Color.Silver);
//             var part38 = @"                /_|.-'\ ,'.           /_|.-'\ ,'.                       ".Pastel(Color.WhiteSmoke);
//             var part39 = @"                  /_,'''\,'             /_,''".Pastel(Color.WhiteSmoke) + @"'\,'                      ".Pastel(Color.WhiteSmoke);

//             return $"{part1}\n{part2}\n{part3}\n{part4}\n{part5}\n{part6}\n{part7}\n{part8}\n{part9}\n{part10}\n{part11}\n{part12}\n{part13}\n{part14}\n{part15}\n{part16}\n{part17}\n{part18}\n{part19}\n{part20}\n{part21}\n{part22}\n{part23}\n{part24}\n{part25}\n{part26}\n{part27}\n{part28}\n{part29}\n{part30}\n{part31}\n{part32}\n{part33}\n{part34}\n{part35}\n{part36}\n{part37}\n{part38}\n{part39}";
//         }